branches:
    only:
        - master

environment:
    matrix:
        - PYTHON: "C:\\Python27-x64"
        # Can't build on 3.4 due to https://github.com/appveyor/ci/issues/1699
        # and/or https://github.com/appveyor/ci/issues/968
        # - PYTHON: "C:\\Python34-x64"
        - PYTHON: "C:\\Python35-x64"
        - PYTHON: "C:\\Python36-x64"

install:
    - "%PYTHON%\\python.exe -m pip install -r developer_requirements.txt"

build: off

test_script:
    - "set PYTHONPATH=%cd%"
    - "set FASTAVRO_USE_CYTHON=1"
    - "%PYTHON%\\python.exe setup.py build_ext --inplace"
    - "%PYTHON%\\python.exe -m pytest -v tests"

after_test:
    # If tests are successful, create binary packages for the project.
    - "set FASTAVRO_USE_CYTHON=1"
    - "%PYTHON%\\python.exe setup.py bdist_wheel"
    - ps: "ls dist"

artifacts:
    # Archive the generated packages in the ci.appveyor.com build report.
    - path: dist\*
